### global defaults ############################################################

mri_ruby_version: 2.1.5

# can be overridden 
database_password: madek

# database
database:
  username: madek
  password: "{{database_password}}"
  hostname: localhost
  port: 5432
  database: madek-v3_production
  pool: 25

