### global defaults ############################################################

file_storage_dir: "{{madek_root_dir}}/storage/originals"
thumbnail_storage_dir: "{{madek_root_dir}}/storage/thumbnails"
download_storage_dir: "{{madek_root_dir}}/tmp/downloads"
zip_storage_dir: "{{madek_root_dir}}/tmp/zipfiles"

mri_ruby_version: 2.1.5

# can be overridden
database_password: madek

# database
database:
  username: madek
  password: "{{database_password}}"
  hostname: localhost
  port: 5432
  database: madek-v3_production
  pool: 25

