###############################################################################
# Madek Default Variables
################################################################################

# This files contains variables for your Madek environment which are
# meant to be overridden for customization.

################################################################################
### global defaults ############################################################
################################################################################

madek_external_base_url: https://{{ madek_external_hostname }}
madek_external_hostname: "{{ ansible_default_ipv4.address }}"

ssh_keys: []
removed_ssh_keys: []

zhdk_integration: False
shibboleth_sign_in_enabled: False

server_timezone: Etc/UTC
rails_timezone: UTC

force_local_build: false

madek_archive_base_url: null
madek_support_email: null

server_journald_forward_to_syslog: "no"

mini_profiler_enabled: no

ansible_python_interpreter: '{% if (ansible_distribution is defined and ansible_distribution == "Ubuntu" and ansible_distribution_release == "focal") %}/usr/bin/python3{% else %}/usr/bin/python{% endif %}'

################################################################################
### Rubies ########################################################################
################################################################################

madek_ruby_versions:
  datalayer: 2.7.6
  graphql_api: 2.7.6
  admin_webapp: 2.7.6
  webapp: 2.7.6

################################################################################
### API ########################################################################
################################################################################

api_cors_enabled: True

################################################################################
### Zencoder Encoding Settings #################################################
################################################################################

zencoder_enabled: False
zencoder_api_key: NULL
zencoder_test_mode: True
zencoder_video_output_formats:
  webm:
    {
      format: "webm",
      label: "webm",
      quality: 4,
      speed: 2,
      width: 620,
      thumbnails: true,
    }
  mp4: { format: "mp4", label: "mp4", video_codec: "h264", width: 620 }

zencoder_video_thumbnails_defaults: { interval: 60, width: 620, format: "jpg" }

zencoder_audio_output_formats:
  mp3: { format: "mp3", audio_codec: "mp3", skip_video: true }

################################################################################
### storage ####################################################################
################################################################################

madek_storage_dir: /var/local/madek-file-storage
madek_file_storage_dir: "{{madek_storage_dir}}/originals"
madek_thumbnail_storage_dir: "{{madek_storage_dir}}/thumbnails"

# uploaded files will be temporarily stored here too:
madek_tmp_dir: "/tmp/madek"

setup_storage_directories: true

################################################################################
### secrets ####################################################################
################################################################################

madek_master_secret: "{{ lookup('password', inventory_dir + '/' + 'master_secret.txt chars=ascii_letters,digits,hexdigits length=40') }}"
madek_database_secret: "{{['database', madek_master_secret ] | join() | hash('sha256') }}"

################################################################################
### feature toggles ############################################################
################################################################################

# alpha feature, NOT for production! enable it by setting it to "on my own risk"
madek_feature_toggle_admin_sql_reports: false
madek_graphql_api_preview_enabled: false

###############################################################################
### http server ###############################################################
#################################################################################

madek_virtual_hosts:
  - hostname: "localhost"
    ip: "localhost"
    logfile_infix: "localhost"
    force_redirect_to_https: no
  - hostname: NULL
    ip: "*"
    ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
    force_redirect_to_https: no

madek_disallow_search_engine_crawlers: no
madek_block_useragents: []
madek_is_behind_gateway: false # set to true if host is behind a HTTP gateway / reverse proxy

################################################################################
### web contexts ###############################################################
################################################################################

madek_base_name: madek
madek_webapp_port: 8880
madek_admin_port: 8881
madek_api_port: 8885
madek_graphql_api_port: 8886

################################################################################
### reset ######################################################################
################################################################################

drop_database: false
restore_structure_and_data: false

################################################################################
### webapp ######################################################################
################################################################################

madek_webapp_html_extra_head_start: ""
madek_webapp_html_extra_head_end: ""
madek_webapp_html_extra_body_start: ""
madek_webapp_html_extra_body_end: ""
madek_webapp_embeds:
  enable_opengraph: true
  twitter_cards_site: false
madek_webapp_xmx_mb: 1000

###############################################################################
###############################################################################
###############################################################################

rails_env: production

secret_key_base: "{{madek_master_secret}}"

madek_configuration_management_url: "http://localhost:{{madek_webapp_port}}/configuration_management_backdoor/invoke"

madek_user: "{{madek_base_name}}"
madek_user_home: "/home/{{madek_user}}"

madek_root_dir: "/{{madek_base_name}}"

madek_server_dir: "{{madek_root_dir}}/server"

madek_api_docs_dir: "{{madek_server_dir}}/api/docs"
madek_api_browser_dir: "{{madek_server_dir}}/api/browser"

madek_webapp_dir: "{{madek_server_dir}}/webapp"
madek_webapp_service_name: "{{madek_base_name}}_webapp"

madek_admin_dir: "{{madek_server_dir}}/admin-webapp"
madek_admin_service_name: "{{madek_base_name}}_admin-webapp"

madek_api_dir: "{{madek_server_dir}}/api"
madek_api_service_name: "{{madek_base_name}}_api"

madek_graphql_api_dir: "{{madek_server_dir}}/api"
madek_graphql_api_service_name: "{{madek_base_name}}_api"

madek_user_docs_dir: "{{madek_root_dir}}/user-docs"
madek_user_docs_web_path: "/hilfe"

# database
postgres_version: 10 # major version, NOTE: this variable is not used yet everywhere
database:
  user: "{{madek_user}}"
  password: "{{madek_database_secret}}"
  hostname: localhost
  port: 5432
  name: "{{madek_base_name}}_production"
  pool: 5 # should be (service.max_threads_per_worker - 1)

madek_services:
  # NOTE: the name of the keys matter for sorting;
  # webapp must be the last in pythons default sorting
  # because it otherwise eats all routes since it is not
  # scoped
  # FIXME: use array (hash key is not important anyways)

  api:
    name: api
    type: java
    active: true
    dir: /api
    http_port: "{{madek_api_port}}"
    context: /api
    main: madek.api.main
    monit_match: 'java.*madek\.api\.main'
    monit_check_urls:
      - http://localhost:{{madek_api_port}}/api/status

  graphql_api:
    name: graphql-api
    type: rails
    active: "{{madek_graphql_api_preview_enabled}}"
    ruby_version: "{{madek_ruby_versions.graphql_api}}"
    max_threads_per_worker: 2
    dir: /graphql-api
    assets_sub_dir: /public/assets
    http_port: "{{madek_graphql_api_port}}"
    context: "/graphql"
    database:
      user: "{{database.user}}-readonly"
      password: "{{database.password}}-readonly"
    xmx: 512m
    monit_match: 'puma.*\:{{madek_graphql_api_port}}'
    monit_check_urls:
      - http://localhost:{{madek_graphql_api_port}}/graphql/graphiql

  admin_webapp:
    name: admin-webapp
    type: rails
    active: true
    ruby_version: "{{madek_ruby_versions.admin_webapp}}"
    max_threads_per_worker: 2
    dir: /admin-webapp
    assets_sub_dir: /public/admin/assets
    http_port: "{{madek_admin_port}}"
    context: "/admin"
    database: { user: "{{database.user}}", password: "{{database.password}}" }
    xmx: 512m
    monit_match: 'puma.*\:{{madek_admin_port}}'
    monit_check_urls:
      - http://localhost:{{madek_admin_port}}/admin/status

  webapp:
    name: webapp
    type: rails
    active: true
    ruby_version: "{{madek_ruby_versions.webapp}}"
    puma_config: "./config/puma.rb"
    max_workers: "{{ansible_processor_vcpus}}"
    max_threads_per_worker: 4
    dir: /webapp
    database: { user: "{{database.user}}", password: "{{database.password}}" }
    assets_sub_dir: /public/assets
    http_port: "{{madek_webapp_port}}"
    context: ""
    monit_match: 'puma.*\:{{madek_webapp_port}}'
    monit_check_urls:
      - http://localhost:{{madek_webapp_port}}/status
