- name: Install postgresql
  apt:
    pkg:
      - sudo
      - libpq-dev
      - postgresql-client-10
      - postgresql-contrib-10
      - postgresql-10
      - python-psycopg2
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]
