- include_tasks: apt.yml

- package_facts:
    manager: auto

- include_tasks: upgrade_95_to_10.yml
  when: "'postgresql-9.5' in ansible_facts.packages"

- include_tasks: install.yml

- include_tasks: root_user.yml

- include_tasks: monitor.yml
