- name: remove previously installed madek server
  file:
    path: "{{madek_server_dir}}"
    state: absent

- name: remove create madek server dir
  file:
    path: "{{madek_server_dir}}"
    state: directory
    mode: 0755

- name: make sure madek root dir is present
  file:
    path: "{{madek_root_dir}}"
    state: directory

- name: make sure /etc/madek/config root dir is present
  file:
    path: "/etc/madek/config"
    state: directory
    mode: 0755

- name: create symlink from server/config to /etc/madek/config
  file:
    src: "/etc/madek/config"
    dest: "{{madek_server_dir}}/config"
    state: link

#- name: add deploy info to file
#  lineinfile:
#    dest: "{{madek_server_dir}}/config/deploy-info.yml"
#    insertafter: "^---$"
#    line: 'deployed: { time: "{{ ansible_date_time.iso8601 }}"}'
#    # validate: python3 -c 'from yaml import load, Loader; load(open(‘%s’), Loader=Loader)'

- name: change owner
  file:
    path: "{{madek_root_dir}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes

- name: Setup storage directories
  shell: 'mkdir -p "{{item}}" && chown -R "{{madek_user}}":"{{madek_user}}" "{{item}}"'
  with_items:
    - "{{madek_file_storage_dir}}"
    - "{{madek_thumbnail_storage_dir}}"
    - "{{madek_tmp_dir}}"
  when: setup_storage_directories


