all:
  vars:
    ip_trixie: 10.211.55.33
    ip_bookworm: 10.211.55.29
    ip_jammy: 10.211.55.34
    ip_resolute: 10.211.55.35
  hosts:
    trixie: # Debian 13 (trixie)
      ansible_host: "{{ ip_trixie }}"
      madek_external_hostname: "{{ ip_trixie }}"
    bookworm: # Debian 12 (bookworm)
      ansible_host: "{{ ip_bookworm }}"
      madek_external_hostname: "{{ ip_bookworm }}"
    jammy: # Ubuntu 22.04 LTS
      ansible_host: "{{ ip_jammy }}"
      madek_external_hostname: "{{ ip_jammy }}"
    resolute: # Ubuntu 26.04 LTS (resolute)
      ansible_host: "{{ ip_resolute }}"
      madek_external_hostname: "{{ ip_resolute }}"
  children:
    madek:
      hosts:
        trixie:
        bookworm:
        jammy:
        resolute:
