- name: dependencies
  apt:
    pkg:
      - monit
      - ruby
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- include: monitor-service.yml
  with_dict: '{{madek_services}}'

- name: reload monit
  service:
    name: monit
    state: reloaded
