- include: setup-apache2.yml
- include: setup-certbot.yml

- name: disable all madek sites
  shell: rm /etc/apache2/sites-enabled/madek_*
  failed_when: false
  register: cmd
  changed_when: cmd.rc != 0

- name: remove madek configurations
  file:
    path: /etc/apache2/madek
    state: absent

- file:
    path: /etc/apache2/madek/
    state: directory
    mode: 0755

- template:
    src: shared.conf
    dest: /etc/apache2/madek/shared.conf
    mode: 0644
  tags:
    - server_setup-munin

- template:
    src: robots.txt
    dest: "{{ madek_webapp_dir }}/public/robots.txt"
    mode: 0644

- debug:
    var: madek_virtual_hosts

- include: virtual-host.yml
  with_indexed_items: '{{madek_virtual_hosts}}'

- name: enable letsencrypt cert if present
  when: '(letsencrypt_check_certbot.rc == 0) and (letsencrypt_cert.stat.exists == True)'
  # NOTE: give config path so it applies to *all* vhosts.
  shell:
    certbot run
      -n --strict-permissions
      --keep-until-expiring
      --redirect --uir --hsts
      --apache --apache-vhost-root /etc/apache2/madek
      -d {{madek_external_hostname}}

- name: reload reverse-proxy
  service:
    name: apache2
    state: reloaded
  tags:
    - server_setup-munin
