- file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{user}}"
    state: directory
    recurse: yes
  with_items:
    - "{{path}}/node_modules"
    - "~{{madek_user}}/.npm"

- name: npm install
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh
          && cd {{madek_webapp_dir}}/
          && npm install' {{madek_user}}
  register: npm_install

- file:
    path: "{{item}}"
    owner: root
    group: root
    state: directory
    recurse: yes
  with_items:
    - "{{path}}/node_modules"
    - "~{{madek_user}}/.npm"
