###############################################################################
# Madek Default Variables
################################################################################

# This files contains variables for your Madek environment which are
# meant to be overridden for customization.

################################################################################
### global defaults ############################################################
################################################################################

madek_host_name: '{{ host_name | default(ansible_default_ipv4.address) }}'
ssh_keys: []

# dont' use single quotes "'"; or quote them
madek_site_title: "Madek@{{madek_host_name}}"
madek_welcome_title: "Welcome to your installation of Madek!"

zhdk_integration: False

server_timezone: Etc/UTC
rails_timezone: UTC

force_local_build: false

################################################################################
### API ########################################################################
################################################################################

api_cors_enabled: False


################################################################################
### Zencoder Encoding Settings #################################################
################################################################################

zencoder_enabled: False
zencoder_api_key: NULL
zencoder_test_mode: True
zencoder_video_output_formats_defaults:
  - {format: 'webm', label: 'webm', quality: 4, speed: 2, width: 620, thumbnails: true}
  - {format: 'mp4', label: 'mp4', video_codec: 'h264'}
zencoder_video_thumbnails_defaults: {interval: 60, width: 620, format: "jpg"}
zencoder_audio_output_formats_defaults: [{audio_codec: 'vorbis', skip_video: true}]


################################################################################
### storage ####################################################################
################################################################################

madek_storage_dir: /var/local/madek-file-storage
file_storage_dir: "{{madek_storage_dir}}/originals"
thumbnail_storage_dir: "{{madek_storage_dir}}/thumbnails"
download_storage_dir: "{{madek_storage_dir}}/tmp/downloads"
zip_storage_dir: "{{madek_storage_dir}}/tmp/zipfiles"

setup_storage_directories: true

################################################################################
### secrets ####################################################################
################################################################################

madek_master_secret: "{{ lookup('password', inventory_dir + '/' + 'master_secret.txt chars=ascii_letters,digits,hexdigits length=40') }}"
madek_database_secret: "{{['database', madek_master_secret ] | join() | hash('sha256') }}"


###############################################################################
### http server ###############################################################
#################################################################################

virtual_hosts:
- hostname: "localhost"
  ip: "localhost"
  logfile_infix: "localhost"
- hostname: NULL
  ip: '*'
  ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key



###############################################################################
### Memory ####################################################################
#################################################################################
# database uses around 20% already

madek_memtotal_mb: '{{ansible_memtotal_mb * 0.7 }}'

webapp_xmx_mb_value: "{{ ((madek_memtotal_mb | float) * 0.4) | round |int }}"
webapp_cache_size_megabytes: "{{ (( madek_memtotal_mb | float) * 0.05) | round | int }}"

admin_xmx_mb_value: "{{ ((madek_memtotal_mb | float) * 0.2) | round |int }}"
admin_cache_size_megabytes: "{{ (( madek_memtotal_mb | float) * 0.05) | round | int }}"

lein_service_xmx_mb_value: "{{ ((madek_memtotal_mb | float) * 0.1) | round | int }}"



################################################################################
### web contexts ###############################################################
################################################################################

madek_base_name: madek
madek_webapp_port: 8880
madek_admin_port: 8881
madek_api_port: 8885


################################################################################
### reset ######################################################################
################################################################################

drop_database: false
restore_data: false

###############################################################################
###############################################################################
###############################################################################

rails_env: production

secret_key_base: '{{madek_master_secret}}'

madek_configuration_management_url: 'http://localhost:{{madek_webapp_port}}/configuration_management_backdoor/invoke'

madek_user: "{{madek_base_name}}"
madek_user_home: "/home/{{madek_user}}"

madek_root_dir: '/{{madek_base_name}}'

madek_server_dir: '{{madek_root_dir}}/server'

madek_api_docs_dir: "{{madek_server_dir}}/api/docs"

madek_webapp_dir: "{{madek_server_dir}}/webapp"
madek_webapp_service_name: "{{madek_base_name}}_webapp"

madek_admin_dir: "{{madek_server_dir}}/admin-webapp"
madek_admin_service_name: "{{madek_base_name}}_admin-webapp"


madek_api_dir: "{{madek_server_dir}}/api"
madek_api_service_name: "{{madek_base_name}}_api"



madek_services:

  # caveat: the name of the keys matter for sorting;
  # webapp must be the last in pythons default sorting
  # because it otherwise eats all routes since it is not
  # scoped

  api:
    name: api
    type: java
    path: /api
    http_port: "{{madek_api_port}}"
    context: /api
    main: madek.api.main
    monit_match: java.*madek\.api\.main

  admin_webapp:

    name: admin-webapp
    type: rails
    path: /admin-webapp
    http_port: "{{madek_admin_port}}"
    context: "/admin"
    max_memory_fraction: 0.15
    cache_store_size_fraction: 0.02
    monit_match: java.*webapp.*puma.*config\.ru.*{{madek_admin_port}}

  webapp:

    name: webapp
    type: rails
    path: /webapp
    http_port: "{{madek_webapp_port}}"
    context: ""
    max_memory_fraction: 0.40
    cache_store_size_fraction: 0.05
    monit_match: java.*webapp.*puma.*config\.ru.*{{madek_webapp_port}}


# database
database:
  user: "{{madek_user}}"
  password: "{{madek_database_secret}}"
  hostname: localhost
  port: 5432
  name: "{{madek_base_name}}_production"
  pool: 10
