# Run Ruby Scripts on a server via ansible, get back a log file
# example: $ bin/ansible-playbook -i inventories/zhdk/hosts_medienarchiv execute-script_play.yml -e 'script_file=inventories/zhdk/extensions/gh362-fix-preview.rb'

- hosts: madek
  roles:
    - role: execute-script
