- hosts: madek
  pre_tasks:
    - name: setup
      setup: {}
      tags: [always]

- hosts: madek-gateway

  roles:
    - role: os-setup
    - role: apache-httpd
    - role: gateway-proxy
      tags: [gateway-proxy]
