---

- hosts: madek

  vars:
    dump_items:
      - data
      - structure_and_data

  tasks:

  - name: Dump
    become: true
    become_user: '{{madek_user}}'
    become_method: su
    shell:  |
      set -eux
      cd {{madek_webapp_dir}}
      export PATH=$(pwd)/vendor/jruby/bin/:$PATH
      export RAILS_ENV=production
      jruby -S bundle exec rake db:pg:{{item}}:dump FILE=/tmp/madek_{{item}}.pgbin
    args:
      executable: /bin/bash
    with_items: "{{dump_items}}"

  - fetch:
      src: /tmp/madek_{{item}}.pgbin
      dest: tmp/
    with_items: "{{dump_items}}"
