- hosts: madek
  gather_facts: False
  pre_tasks:
    - name: install system python
      raw: apt install -y python3

- hosts: localhost
  roles:
    - role: find_or_build_archive

- hosts: madek
  roles:
    - role: os-check
    - role: pre-cleanup
    - role: os-setup
    - role: dependencies
    - role: postgresql
    - role: apache-httpd
    - role: madek-user
    - role: get-archive
    - role: server-dir_set-up
    - role: asdf
      asdf_user: '{{madek_user}}'
    - role: madek-configuration
    - role: madek-datalayer
    - role: services
    - role: watchdog
    - role: reverse-proxy
    - role: db-backups
