- hosts: madek

  tasks:
    - name: Dump
      become: true
      become_user: root
      shell: |
        #!/usr/bin/env bash
        set -euo pipefail
        sudo -u "{{madek_user}}" -- bash -eux -c '
          cd {{madek_webapp_dir}}
          export RAILS_ENV=production
          export SECRET_KEY_BASE_DUMMY=1
          /usr/local/bin/chruby-exec ruby-{{madek_ruby_versions.webapp}} -- \
            bundle exec rake db:pg:structure_and_data:dump FILE=/tmp/madek.pgbin
        '
      args:
        executable: /bin/bash
        warn: no

    - fetch:
        src: /tmp/madek.pgbin
        dest: tmp/
