- hosts: madek

  vars_files:
    - vars.yml

  roles:
    - role: debuntu-setup

    - role: postgresql
    - role: ftp-server

    - role: apache-httpd

    - role: server-reverse-proxy
      site_online: False

    - role: git-checkout
      git_checkout_target_path: "{{madek_root_dir}}"
      git_checkout_repo: "https://github.com/Madek/madek.git"
      git_checkout_version: "{{ lookup('pipe','cd  ./../. && git log -n 1 --format=%H') }}"

    - role: madek-user

    - role: madek-datalayer

    - role: lein-service
      lein_service_name: "{{madek_api_service_name}}"
      lein_service_app_dir: "{{madek_api_dir}}"
      lein_service_user: "{{madek_user}}"

    - role: madek-webapp

    - role: madek-permissions-lockdown

    - role: madek-set-data

    - role: server-reverse-proxy

#
#    - role: db-backups
#      tags: [db-backups]
#
#    - role: madek-dropbox
#
#    - role: madek-zencoder
#      tags: [zencoder]
#
