- hosts: localhost

  roles:

    - role: find_or_build_archive
      tags:
        - find_or_build_archive
        - get-archive

- hosts: madek

  roles:

    - role: pre-cleanup
      tags: [pre-cleanup]

    - role: os-setup
      tags: [os-setup]

    - role: openjdk8_install

    - role: postgresql
      tags: [postgresql]

    - role: apache-httpd

    - role: madek-user
      tags: [madek-user]

    - role: get-archive
      tags: [get-archive]

    - role: server-dir_set-up
      tags: [server-dir_set-up]

    - role: madek-configuration
      tags: [madek-configuration]

    - role: madek-datalayer
      tags: [madek-datalayer]

    - role: services
      tags: [services]

    - role: monitoring
      tags: [monitoring]

    - role: reverse-proxy
      tags: [reverse-proxy]

    - role: madek-set-data
      tags: [set-data]

#    - role: db-backups
#      tags: [db-backups]
