- hosts: madek
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_user: root
  pre_tasks:
    - name: install system python
      raw: apt install -y python3

# TODO ReverseProxy like in Leihs

- hosts: madek
  roles:
    - role: defaults
      tags: [always]
    - role: os-check
    - role: pre-cleanup
      tags: [pre-cleanup]
    - role: os-setup
    - role: dependencies
      tags: ['dependencies']
    - role: reverse-proxy-pre-setup
      tags: [reverse-proxy, reverse-proxy-pre-setup]
    - role: postgresql
      tags: [postgresql]
    - role: apache-httpd
    - role: reverse-proxy-maintenance
      tags: [reverse-proxy-maintenance, maintenance]
    - role: madek-user
    - role: server-dirs
      tags: [server-dirs]
    - role: asdf
      asdf_user: '{{madek_user}}'
    - role: server-config
      tags: [server-config]
    # todo check db backup on deploy
    - role: service-datalayer
      tags: [datalayer]
    - role: service-admin-webapp
      tags: [admin-webapp]
    - role: ../webapp/deploy/roles/deploy
      tags: [webapp]
    - role: ../auth/deploy/roles/deploy
      tags:  [auth]
    - role: service-mail
      tags:  [service-mail]
    - role: ../api/deploy/roles/install
      tags:  [api]
    - role: ../api-v2/deploy/roles/deploy
      tags:  [api-v2]
    - role: timer-jobs
      tags:  [timer-jobs]
    - role: webstats
      tags: [webstats]
    - role: reverse-proxy-madek
      tags: [reverse-proxy-madek]
    - role: ../webapp/deploy/roles/sitemap
      tags: [sitemap]
    - role: db-backups
      tags: [db-backups]
