- name: upload archive to the server
  synchronize:
    src: "{{item}}"
    dest: /tmp/{{item}}
  when: hostvars.localhost.download_archive_url_prefix is not defined
  with_items:
    - madek.tar.gz

- name: download archive to the server
  get_url:
    url: '{{hostvars.localhost.download_archive_url_prefix}}/{{item}}'
    dest: /tmp/{{item}}
    force: yes
  when: hostvars.localhost.download_archive_url_prefix is defined
  with_items:
    - madek.tar.gz
    - madek.tar.gz.sig

- name: copy public key to the server
  copy:
    src: crypto/madek.pub.pem
    dest: /tmp/madek.pub.pem
  when: hostvars.localhost.download_archive_url_prefix is defined

- name: verify archive
  shell: >
    openssl dgst -verify /tmp/madek.pub.pem
    -signature /tmp/madek.tar.gz.sig /tmp/madek.tar.gz
  when: hostvars.localhost.download_archive_url_prefix is defined
