- name: fail os check
  vars:
    min_ubuntu_version: "22.04"
    min_debian_version: "11"
  fail:
    msg: >
      The supported operating systems are Ubuntu >= {{ min_ubuntu_version }} and Debian >= {{ min_debian_version }}
  when: >
    not
    (((ansible_facts['distribution'] == "Ubuntu") and (ansible_facts['distribution_version'] is version(min_ubuntu_version, '>=')))
    or
    ((ansible_facts['distribution'] == "Debian") and (ansible_facts['distribution_version'] is version(min_debian_version, '>='))))


