- name: Add the group
  group:
    name: "{{madek_user}}"
    system: true

- name: Add the user
  user:
    name: "{{madek_user}}"
    group: "{{madek_user}}"
    home: "{{madek_user_home}}"
    system: yes
    shell: /bin/bash

- name: Create or update postgresql user
  postgresql_user:
    name: "{{database.user}}"
    password: "{{database.password}}"
    role_attr_flags: CREATEDB,SUPERUSER
    login_user: root
    port: 5415
