zhdk:
  hosts:

    prod:
      ansible_ssh_host: zhdk-madek-prod.ruby.zhdk.ch
      madek_external_hostname: medienarchiv.zhdk.ch

    staging:
      ansible_ssh_host: zhdk-madek-staging.ruby.zhdk.ch
      madek_external_hostname: staging.madek.zhdk.ch

    test:
      ansible_ssh_host: zhdk-madek-test.ruby.zhdk.ch
      madek_external_hostname: test.madek.zhdk.ch

    test-blank:
      ansible_ssh_host: zhdk-madek-test-blank.ruby.zhdk.ch
      madek_external_hostname: test-blank.madek.zhdk.ch

    jan: {}
    manuel: {}
    nimaai: {}
    tom: {}
    uvb: {}


dev:
  hosts:
    jan: {}
    manuel: {}
    nimaai: {}
    tom: {}
    uvb: {}
  vars:
    ansible_host: '{{inventory_hostname}}-madek.ruby.zhdk.ch'
    external_hostname: '{{inventory_hostname}}.madek.rubydev.zhdk.ch'


non_prod:
  children:
    dev:
  hosts:
    staging:
    test:
    test-blank:


secrets:
  children:
    zhdk:

madek:
  children:
    zhdk:

