- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-httplib2

- wait_for:
    port: "{{madek_webapp_port}}"
    timeout: 600
    state: started

- uri:
    url: "{{madek_configuration_management_url}}"
    timeout: 300
    user: ansible
    password: "{{secret_key_base}}"
    force_basic_auth: yes
    method: POST
    HEADER_Content-Type: application/ruby
    register: previous_uri
    body: |
      AppSettings.find_or_create_by(id: 0) \
        .update_attributes! site_title: '{{madek_site_title}}'
  when: not not madek_site_title


- uri:
    url: "{{madek_configuration_management_url}}"
    timeout: 300
    user: ansible
    password: "{{secret_key_base}}"
    force_basic_auth: yes
    method: POST
    HEADER_Content-Type: application/ruby
    register: previous_uri
    body: >
      AppSettings.find_or_create_by(id: 0) \
        .update_attributes! welcome_title: '{{madek_welcome_title}}'
  when: not not madek_welcome_title
