- name: install various build dependencies
  apt:
    pkg:
      - autoconf
      - bison
      - build-essential
      - libdb-dev
      - libffi-dev
      - libgdbm-dev
      - libgdbm6
      - libgmp-dev
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - patch
      - rustc
      - uuid-dev
      - zlib1g-dev
    update_cache: yes
    cache_valid_time: 3600


- name: install asdf
  become: yes
  become_user: "{{ asdf_user }}"
  shell: |
    #!/bin/bash
    set -euo pipefail
    if [ ! -d ~/.asdf ]; then
      git clone https://github.com/asdf-vm/asdf.git {{asdf_root_dir}}
    fi
    cd {{asdf_root_dir}}
    git fetch --all
    git checkout -f {{asdf_version}}
  args:
    executable: /bin/bash

- name: set bash env for asdf
  blockinfile:
    path: /home/{{asdf_user}}/.bashrc
    owner: '{{asdf_user}}'
    group: '{{asdf_user}}'
    block: |
      source {{asdf_root_dir}}/asdf.sh
      source {{asdf_root_dir}}/completions/asdf.bash
