- name: 'lock madek home and app dir for writing'
  file:
    path: "{{item}}"
    owner: root
    group: root
    state: directory
    recurse: yes
  with_items:
    - "~{{madek_user}}"
    - "{{git_checkout_target_path}}"

- name: 'set needed directory permissions for madek user (optional)'
  file:
    path: "{{item}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes
  with_items:
    - "{{file_storage_dir}}"
    - "{{thumbnail_storage_dir}}"
    - "{{download_storage_dir}}"
    - "{{zip_storage_dir}}"
  ignore_errors: yes


- name: 'set needed directory permissions for madek user'
  file:
    path: "{{item}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes
  with_items:
    - "{{madek_root_dir}}/tmp"
    - "{{madek_webapp_dir}}/tmp"
    - "{{madek_webapp_dir}}/log"
    - "{{madek_webapp_dir}}/public/assets"
    # server-side js rendering needs this!
    - "{{madek_webapp_dir}}/tmp/cache/assets"
    - "{{madek_webapp_dir}}/tmp/cache/browserify-rails"
