- name: Configure database for {{service.name}}
  template:
    src: database.yml
    dest: "{{madek_server_dir}}{{service.dir}}/config/database.yml"
    owner: "{{madek_user}}"
    mode: 0755

- name: Configure secrets for {{service.name}}
  template:
    src: geheimnisse.yml
    dest: "{{madek_server_dir}}{{service.dir}}/config/secrets.yml"
    owner: "{{madek_user}}"
  register: secret

- name: Configure settings.local for {{service.name}}
  template:
    src: settings.local.yml
    dest: "{{madek_server_dir}}/config/settings.local.yml"
    mode: 0755
    owner: "{{madek_user}}"
