- name: Configure database for {{service.name}}
  template:
    src: database.yml
    dest: "{{madek_server_dir}}{{service.dir}}/config/database.yml"
    mode: 0755

- name: Configure secrets for {{service.name}}
  template:
    src: geheimnisse.yml
    dest: "{{madek_server_dir}}{{service.dir}}/config/secrets.yml"
  register: secret


