- name: Setup storage directories
  file:
    path: "{{item}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes
  with_items:
    - "{{file_storage_dir}}"
    - "{{thumbnail_storage_dir}}"
    - "{{download_storage_dir}}"
    - "{{zip_storage_dir}}"
  when: setup_storage_directories

- name: Configure database
  template:
    src: database.yml
    dest: "{{madek_webapp_dir}}/config/database.yml"
    mode: 0755
  register: database_config

- name: Configure database
  template:
    src: database.yml
    dest: "{{madek_admin_dir}}/config/database.yml"
    mode: 0755
  register: database_config

- template:
    src: secrets.yml
    dest: "{{madek_webapp_dir}}/config/secrets.yml"
  register: secret

- template:
    src: settings.local.yml
    dest: "{{madek_root_dir}}/config/settings.local.yml"
    mode: 0755
