# FIXME: https://github.com/ansible/ansible/issues/39456
- name: Setup storage directories
  shell: 'mkdir -p "{{item}}" && chown -R "{{madek_user}}":"{{madek_user}}" "{{item}}"'
  # file:
  #   path: "{{item}}"
  #   owner: "{{madek_user}}"
  #   group: "{{madek_user}}"
  #   state: directory
  #   recurse: yes
  with_items:
    - "{{madek_file_storage_dir}}"
    - "{{madek_thumbnail_storage_dir}}"
    - "{{madek_tmp_dir}}"
  when: setup_storage_directories
  # TODO: can fail on storage read only instances (will fail on HFG and HSLU staging)
  # go back to file module and remove this or remove comments and keep the hack
  ignore_errors: yes

- name: Configure services
  include: configure_services.yml
  with_dict: '{{madek_services}}'


- template:
    src: geheimnisse.yml
    dest: "{{madek_webapp_dir}}/config/secrets.yml"
  register: secret

- template:
    src: settings.local.yml
    dest: "{{madek_server_dir}}/config/settings.local.yml"
    mode: 0755
