- name: Setup storage directories
  file:
    path: "{{item}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes
  with_items:
    - "{{file_storage_dir}}"
    - "{{thumbnail_storage_dir}}"
    - "{{download_storage_dir}}"
    - "{{zip_storage_dir}}"
  when: setup_storage_directories

- name: Configure services
  include: configure_services.yml
  with_dict: '{{madek_services}}'


- template:
    src: secrets.yml
    dest: "{{madek_webapp_dir}}/config/secrets.yml"
  register: secret

- template:
    src: settings.local.yml
    dest: "{{madek_server_dir}}/config/settings.local.yml"
    mode: 0755
