- name: Install webapp dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - memcached
    - libimage-exiftool-perl
    - imagemagick


### secrets ####################################################################

- name: Create secrets
  template: src=secrets.yml
            dest={{madek_webapp_dir}}/config/secrets.yml
            owner={{madek_user}}
            group={{madek_user}}
            mode=0600
  register: secret

### logs #######################################################################

- name: Configure logrotation
  template:
    src: logrotate
    dest: "/etc/logrotate.d/{{madek_webapp_service_name}}"

### Shared Service #############################################################

- template: src=wrapper.sh
            dest={{madek_webapp_wrapper_bin}}
            mode=755
  register: madek_webapp_wrapper

- template: src=start.sh
            dest={{madek_webapp_service_bin}}
            mode=755
  register: madek_webapp_start


### Upstart Service ############################################################

- template: src=init.conf
            dest=/etc/init/cider-ci_user-interface.conf
  register: init_script
  when: ansible_distribution_release == 'trusty'


### Systemd Service ############################################################

- template:
    src: service.conf
    dest: "/etc/systemd/system/{{madek_webapp_service_name}}.service"
  register: madek_webapp_systemd_service
  when: not ansible_distribution_release == 'trusty'


- service:
    name: "{{madek_webapp_service_name}}"
    enabled: yes

- command: logrotate -f /etc/logrotate.d/{{madek_webapp_service_name}}
  ignore_errors: yes

- service:
    name: "{{madek_webapp_service_name}}"
    state: restarted

- service:
    name: "{{madek_webapp_service_name}}"
    state: started
