- name: remove previously installed cider-ci server
  file:
    path: '{{madek_server_dir}}'
    state: absent

- name: marke sure madek root dir is present
  file:
    path: '{{madek_root_dir}}'
    state: directory

- name: unpack and move archive in place
  shell: |
    set -eux
    cd {{madek_root_dir}}
    tar xf /tmp/madek.tar.gz
    mv {{madek_root_dir}}/madek {{madek_server_dir}}

- name: change owner
  file:
    path: "{{madek_root_dir}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes

