- name: remove previously installed madek server
  file:
    path: '{{madek_server_dir}}'
    state: absent

- name: make sure madek root dir is present
  file:
    path: '{{madek_root_dir}}'
    state: directory

- name: unpack and move archive in place
  shell: |
    set -eux
    cd {{madek_root_dir}}
    tar xf /tmp/madek.tar.gz
    mv {{madek_root_dir}}/madek {{madek_server_dir}}

- name: add deploy info to file
  lineinfile:
    dest: "{{madek_server_dir}}/config/deploy-info.yml"
    insertafter: '^---$'
    # NOTE: `build_is_latest_release` set by `find_or_build_archive` role
    line: 'deployed: { time: "{{ ansible_date_time.iso8601 }}", is_release: {{ hostvars.localhost.build_is_latest_release|trim }} }'
    validate: ruby -e 'require "yaml"; YAML.safe_load(File.read("%s"))'

- name: change owner
  file:
    path: "{{madek_root_dir}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes
