- name: fetch git tags
  shell: 'git fetch --tags --recurse-submodules=no'

- name: build combined releases.yml file
  shell: '../dev/releasenotes-md-to-yaml.rb'

- search_download_archive:
    base_url: '{{madek_archive_base_url}}'
  register: search_download_archive
  tags: [debug]

- debug:
    var: search_download_archive
  tags: [debug]

# set some default
- set_fact:
    build_is_latest_release: FALSE

- set_fact:
    download_urls: "{{search_download_archive.urls}}"
    build_is_latest_release: "{{search_download_archive.build_is_latest_release}}"
  when: >
    (search_download_archive.urls is not none)
    and (not force_local_build)
  tags: [debug]

- debug:
    var: download_urls
  tags: [debug]

- debug:
    var: build_is_latest_release
  tags: [debug]
