- name: remove possibly exisiting archive
  file:
    path: '{{playbook_dir}}/tmp/legacy.tar.gz'
    state: absent
  delegate_to: localhost

- name: create archive
  args: { warn: no }
  command: 'tar --exclude-vcs --exclude-vcs-ignores -cz -f "{{playbook_dir}}/tmp/dummy.tar.gz" -C "{{playbook_dir}}/madek-rails-dummy" .'
  delegate_to: localhost

- file:
    path: '{{madek_rails_dummy_path}}'
    state: absent
  name: remove existing dir

- file:
    path: '{{madek_rails_dummy_path}}'
    state: directory
    owner: '{{madek_rails_dummy_user}}'
    recurse: yes
  name: create empty dir

# - file:
#     path: /tmp/dummy.tar.gz
#     state: absent
#   name: remove existing archive

- unarchive:
    src: '{{playbook_dir}}/tmp/dummy.tar.gz'
    dest: '{{madek_rails_dummy_path}}'
    owner: '{{madek_rails_dummy_user}}'
  name: extract archive
