- name: create madek-rails-dummy user
  user:
    name: '{{madek_rails_dummy_user}}'
    shell: /bin/bash
    system: yes

- import_tasks: install-project.yml
- import_tasks: install-ruby.yml
- import_tasks: database.yml
- import_tasks: service.yml
