- name: create madek-rails-dummy user
  user:
    name: '{{madek_rails_dummy_user}}'
    shell: /bin/bash
    system: yes

- include_tasks: install-project.yml
- include_tasks: install-ruby.yml
- include_tasks: database.yml

- include: service.yml
