- name: DB Defaults
  become: true
  become_user: "{{madek_user}}"
  shell: |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    jruby -S bundle exec rake db:pg:terminate_connections db:defaults
