- name: DB Defaults
  become: true
  become_user: '{{madek_user}}'
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    source ~/.asdf/asdf.sh
    cd {{madek_webapp_dir}}
    export RAILS_ENV={{rails_env}}
    bundle exec rake db:pg:terminate_connections db:defaults
  args:
    executable: /bin/bash

