- name: install cron job services
  template: 
    src: "{{item}}.service"
    dest: "/etc/systemd/system/{{item}}.service"
    mode: 0644
  with_items: "{{ timer_job_names }}"

- name: install cron job timers
  template: 
    src: "{{item}}.timer"
    dest: "/etc/systemd/system/{{item}}.timer"
    mode: 0644
  with_items: "{{ timer_job_names }}"

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: ensure cron job services are stopped and disabled
  service:
    name: '{{item}}.service'
    state: stopped
    enabled: false
  with_items: "{{ timer_job_names }}"

- name: enable and start cron job timers
  service:
    name: '{{item}}.timer'
    state: started
    enabled: true
  with_items: "{{ timer_job_names }}"
