- name: install service from template
  template:
    src: madek-auth.service
    dest: /etc/systemd/system/madek-auth.service
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes
  failed_when: false

- name: (re)start auth-service
  service:
    name: madek-auth
    state: restarted
