use_x_sendfile: true
zhdk_integration: {{zhdk_integration}}

madek_master_secret: {{madek_master_secret}}
madek_host_name: {{madek_host_name}}

file_storage_dir: "{{file_storage_dir}}"
thumbnail_storage_dir: "{{thumbnail_storage_dir}}"
download_storage_dir: "{{download_storage_dir}}"
zip_storage_dir: "{{zip_storage_dir}}"


zencoder_enabled: {{zencoder_enabled}}
zencoder_api_key: {{zencoder_api_key}}
zencoder_test_mode: {{zencoder_test_mode}}
zencoder_video_output_formats_defaults: {{zencoder_video_output_formats_defaults}}
zencoder_video_thumbnails_defaults: {{zencoder_video_thumbnails_defaults}}
zencoder_audio_output_formats_defaults: {{zencoder_audio_output_formats_defaults}}



database:
  adapter: "postgresql"
  classname: "org.postgresl.Driver"
  subname: '//localhost:{{database.port}}/{{database.name}}'
  subprotocol: "postgresql"
  user: "{{database.user}}"
  password: "{{database.password}}"
  max_pool_size: 3

webapp_cache_size_megabytes: {{webapp_cache_size_megabytes}}

services:

  api:

    http:

      host: localhost
      port: {{madek_api_port}}
      context: {{madek_web_context_or_empty}}
      sub_context: /api
      ssl: false


