### shared site  ##############################################################

- file: path=/etc/apache2/shared
        state=directory
        mode=0755

- file:
    path: "{{madek_host_apps_path}}"
    state: touch

- name: template site online include
  template:
    src: shared-site.apache.conf
    dest: /etc/apache2/shared/{{madek_base_name}}_site.conf
    mode: 0644
  when: site_online


- name: template site offline include
  template:
    src: shared-site_offline.apache.conf
    dest: /etc/apache2/shared/{{madek_base_name}}_site.conf
    mode: 0644
  when: not site_online

- lineinfile:
    dest: "{{madek_host_apps_path}}"
    line: "Include /etc/apache2/shared/{{madek_base_name}}_site.conf"


### http site #################################################################

- template:
    src: site.apache.conf
    dest: /etc/apache2/sites-available/{{madek_host_name}}.conf
    mode: 0644

- command: a2ensite {{madek_host_name}}


### https site ################################################################

- template:
    src: site_https.apache.conf
    dest: /etc/apache2/sites-available/{{madek_host_name}}_https.conf
    mode: 0755
  register: reverse_proxy_https_site

- command: a2ensite {{madek_host_name}}_https


### reload ####################################################################

- service:
    name: apache2
    state: reloaded
