### offline ###################################################################

- template:
    src: offline.apache.conf
    dest: /etc/apache2/sites-available/offline.conf
    mode: 0644

- command: a2ensite offline
  when: not reverse_proxy_enabled

- command: a2dissite offline
  when: reverse_proxy_enabled

- template:
    src: offline_https.apache.conf
    dest: /etc/apache2/sites-available/offline_https.conf
    mode: 0755

- command: a2ensite offline_https
  when: not reverse_proxy_enabled

- command: a2dissite offline_https
  when: reverse_proxy_enabled



### shared site  ##############################################################

- file: path=/etc/apache2/shared
        state=directory
        mode=0755

- file:
    path: "{{madek_host_apps_path}}"
    state: touch

- template:
    src: shared-site.apache.conf
    dest: /etc/apache2/shared/madek_{{madek_webapp_name}}_site.conf
    mode: 0644


- lineinfile:
    dest: "{{madek_host_apps_path}}"
    line: "Include /etc/apache2/shared/madek_{{madek_webapp_name}}_site.conf"

### http site #################################################################

- template:
    src: site.apache.conf
    dest: /etc/apache2/sites-available/madek_{{madek_host_name}}.conf
    mode: 0644

- command: a2ensite madek_{{madek_host_name}}
  when: reverse_proxy_enabled

- command: a2dissite madek_{{madek_host_name}}
  when: not reverse_proxy_enabled


### https site ################################################################

- template:
    src: site_https.apache.conf
    dest: /etc/apache2/sites-available/madek_{{madek_host_name}}_https.conf
    mode: 0755
  register: reverse_proxy_https_site

- command: a2ensite madek_{{madek_host_name}}_https
  when: reverse_proxy_enabled

- command: a2dissite madek_{{madek_host_name}}_https
  when: not reverse_proxy_enabled

### reload ####################################################################

- service:
    name: apache2
    state: reloaded

