- name: stop monit
  service:
    name: monit
    state: stopped
  failed_when: false

- name: remove monit madek service monitoring
  shell: rm -rf /etc/monit/conf.d/cider-ci_*  /etc/monit/conf.d/madek_*

- name: stop all madek services
  shell:
    systemctl list-unit-files --type=service
    | awk '{print $1}'
    | grep madek
    | xargs systemctl stop
  failed_when: false

- name: remove madek units
  shell: rm -f /etc/systemd/system/madek*
  failed_when: false

- name: reload systemd
  shell: systemctl daemon-reload
  failed_when: false

- name: kill all remaining processes of the user madek
  shell: pkill -u {{madek_user}}
  failed_when: false


