- name: stop monit
  service:
    name: monit
    state: stopped
  failed_when: false

- name: remove monit madek service watchdog
  shell: rm -rf /etc/monit/conf.d/cider-ci_*  /etc/monit/conf.d/madek_*

- name: stop all madek services
  service:
    name: madek-{{item}}
    enabled: no
    state: stopped
  with_items:
    - admin-webapp
    - api
    - api-v2
    - auth
    - datalayer
    - mail
    - webapp
  failed_when: false

- name: reload systemd
  shell: systemctl daemon-reload

- name: kill all remaining processes of the user madek
  shell: pkill -u {{item}}
  with_items:
    - madek
    - madek-auth
  failed_when: false
