- name: stop monit
  service:
    name: monit
    state: stopped
  failed_when: false

- name: remove monit madek service watchdog
  shell: rm -rf /etc/monit/conf.d/cider-ci_*  /etc/monit/conf.d/madek_*

- name: stop all madek services
  shell: systemctl stop madek*
  failed_when: false

- name: remove madek units
  shell: rm -f /etc/systemd/system/madek*

- name: reload systemd
  shell: systemctl daemon-reload

- name: kill all remaining processes of the user madek
  shell: pkill -u {{item}}
  with_items:
    - madek
    - madek-auth
  failed_when: false
