### specific settings for host madek-test ###################################

madek_webapp_port: 8880
madek_webapp_context: "/madek-v3"
host_name: test8.madek.zhdk.ch
secret_key_base: secret

webapp:
  color_scheme: blue
  custom_color: '#6149c1' # purple

### Zencoder ##################################################################

zencoder_enabled: False
zencoder_test_mode: True


### Zhdk ######################################################################

zhdk_integration: True
ntp_server: ntp.zhdk.ch

ssh_keys:
- "{{lookup('file', './ssh_keys/drtom')}}"
- "{{lookup('file', './ssh_keys/mfa')}}"
- "{{lookup('file', './ssh_keys/nimaai')}}"
- "{{lookup('file', './ssh_keys/rca')}}"


removed_ssh_keys: []

primary_hostname: test.madek.zhdk.ch

### Path adjustmens for mounts


### Backups ###################################################################
db_backups_enabled: False


### Passenger #################################################################
passenger_min_instances: 1
passenger_max_pool_size: 1

