- name: Install dependencies
  apt:
    pkg:
      - imagemagick
      - libimage-exiftool-perl
      - ruby
      - nodejs
      - openjdk-11-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600

