- name: Install dependencies
  apt:
    pkg:
      - ghostscript
      - imagemagick
      - libimage-exiftool-perl
      - nodejs
      - ruby
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: fix imagemagick configuration to allow PDF preview generation
  lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    state: present
    search_string: '<policy domain="coder" rights="none" pattern="PDF" />'
    line: '  <policy domain="coder" rights="read | write" pattern="PDF" />'
    insertafter: 'ghostscript format types'

- name: Install OpenJDK 11 on Debian 10
  apt:
    pkg:
      - openjdk-11-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10")

- name: Install OpenJDK 17 on all other than Debian 10
  apt:
    pkg:
      - openjdk-17-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: not (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10")
