- name: DB smtp_settings -- set enabled to TRUE
  become: true
  become_user: '{{madek_user}}'
  shell: |
    /usr/lib/postgresql/15/bin/psql --port 5415 {{database.name}} -c \
      "UPDATE smtp_settings SET is_enabled = TRUE;"
  when: madek_send_mails

- name: DB smtp_settings -- set enabled to FALSE
  become: true
  become_user: '{{madek_user}}'
  shell: |
    /usr/lib/postgresql/15/bin/psql --port 5415 {{database.name}} -c \
      "UPDATE smtp_settings SET is_enabled = FALSE;"
  when: not madek_send_mails
 
