- service:
    name: "{{madek_webapp_service_name}}"
    state: stopped
  failed_when: false

- command: logrotate -f /etc/logrotate.d/{{madek_webapp_service_name}}
  failed_when: false

- file:
    path: "{{madek_root_dir}}"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes

- name: Drop DB
  become: true
  become_user: "{{madek_user}}"
  shell: |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    jruby -S bundle exec rake db:pg:terminate_connections db:drop
  when: drop_database or restore_data
  ignore_errors: true

- name: Migrate to 100
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export RAILS_ENV={{rails_env}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export VERSION=100
    jruby -S bundle exec rake db:create db:migrate
  register: migrate
  when: drop_database or restore_data
  changed_when: not migrate.stdout | match("")

- name: Restore data
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    export FILE={{db_data_file}}
    export JRUBY_OPTS=" -J-Xmx8G "
    jruby -S bundle exec rake db:pg:terminate_connections
    jruby -S bundle exec rake db:pg:terminate_connections db:pg:truncate_tables db:pg:data:restore
  register: migrate
  when: restore_data
  changed_when: not migrate.stdout | match("")

- name: Migrate rest
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    export JRUBY_OPTS=" -J-Xmx8G "
    jruby -S bundle exec rake db:create db:migrate
  register: migrate
  tags: madek-datalayer-migrate-rest
  changed_when: not migrate.stdout | match("")

- name: Seed (set core data)
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    export JRUBY_OPTS=" -J-Xmx2G "
    jruby -S bundle exec rake db:seed

- file:
    path: "{{madek_webapp_dir}}/db"
    owner: root
    group: root
    state: directory
    recurse: yes

