- service:
    name: "{{madek_webapp_service_name}}"
    state: stopped
  failed_when: false

- command: logrotate -f /etc/logrotate.d/{{madek_webapp_service_name}}
  failed_when: false

# FIXME: https://github.com/ansible/ansible/issues/39456
- name: change owner
  shell: 'chown -R "{{madek_user}}":"{{madek_user}}" "{{madek_root_dir}}"'
# - file:
#     path: "{{madek_root_dir}}"
#     owner: "{{madek_user}}"
#     group: "{{madek_user}}"
#     state: directory
#     recurse: yes

- name: Drop DB
  become: true
  become_user: "{{madek_user}}"
  shell: |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    jruby -S bundle exec rake db:pg:terminate_connections db:drop
  when: drop_database or restore_structure_and_data
  ignore_errors: true
  tags: [drop-db]

- name: Create DB
  become: true
  become_user: "{{madek_user}}"
  shell: |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    jruby -S bundle exec rake db:create
  ignore_errors: true

- name: Restore structure and data
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    set -eux
    pg_restore --exit-on-error --single-transaction -x -O -d '{{database.name}}' '{{restore_structure_and_data_file}}'
  register: restore
  when: restore_structure_and_data
  changed_when: not restore.stdout | match("")
  tags: [restore_structure_and_data]

- name: Migrate
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    set -eux
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    export JRUBY_OPTS=" -J-Xmx2G "
    jruby -S bundle exec rake db:migrate
  register: migrate
  changed_when: not migrate.stdout | match("")

- name: Seed (set core data)
  become: true
  become_user: "{{madek_user}}"
  shell:  |
    #!/usr/bin/env bash
    cd {{madek_webapp_dir}}
    export PATH=$(pwd)/vendor/jruby/bin/:$PATH
    export RAILS_ENV={{rails_env}}
    export JRUBY_OPTS=" -J-Xmx2G "
    jruby -S bundle exec rake db:seed

# FIXME: https://github.com/ansible/ansible/issues/39456
- name: create DB dir, change owner to root
  shell: "mkdir -p '{{madek_webapp_dir}}/db' && chown -R root:root '{{madek_webapp_dir}}/db'"
# - file:
#     path: "{{madek_webapp_dir}}/db"
#     owner: root
#     group: root
#     state: directory
#     recurse: yes
