- name: Add backports repository for Debian buster
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
  tags: [internet]
  when: '(ansible_distribution == "Debian" and ansible_distribution_release == "buster")'

- name: dist upgrade
  apt: upgrade=dist update_cache=yes cache_valid_time=3600

### Install some stuff we need ###############################################

- name: Install basic packages
  apt: pkg={{packages}} state=latest update_cache=yes cache_valid_time=3600
  vars:
    packages:
      # - ruby
      - htop
      - python-passlib

### set timezone ##############################################################

- name: Set timezone variables
  copy:
    content: "{{server_timezone}}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: set_etc_timezone

- name: reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: set_etc_timezone.changed

### journald and syslog #######################################################

- name: configure journald ForwardToSyslog
  lineinfile:
    dest: /etc/systemd/journald.conf
    line: ForwardToSyslog={{server_journald_forward_to_syslog}}
    regexp: ForwardToSyslog
  register: journald_config

- name: reload systemd
  shell: systemctl force-reload systemd-journald
  when: journald_config.changed

### Vim as default editor #####################################################

- name: Install vim-nox
  apt: pkg=vim-nox state=latest update_cache=yes cache_valid_time=3600
  register: install_vim_nox

- name: Set vim-nox as default editor
  command: update-alternatives --set editor /usr/bin/vim.nox
  register: result
  # FIXME: this is broken in newer ansible (but also not really important)
  # changed_when: 'result.stdout | search("using \/usr\/bin\/vim\.nox")'

- lineinfile:
    dest: "{{ansible_env.HOME}}/.bashrc"
    line: set -o vi
  when: madek_vim_mode == true

### etckeeper #################################################################

- include: Debuntu_etckeeper.yml

### monit #####################################################################

- include: Debuntu_monit.yml
  tags:
    - os-setup_monit

### vmware ####################################################################

- name: install vmware tools
  apt: name={{packages}} state=latest update_cache=yes cache_valid_time=3600
  when: ansible_virtualization_type == "VMware"
  vars:
    packages:
      - open-vm-tools
      - open-vm-tools-dkms
