- authorized_key:
    user: root
    key: "{{item}}"
  with_items: '{{ssh_keys}}'

- authorized_key:
    user: root
    key: "{{item}}"
    state: absent
  with_items: '{{removed_ssh_keys}}'

- include: Debuntu.yml
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_major_version|int >= 7)

- include: Debuntu.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_major_version|int >= 8)
