- name: remove global rbenv-load
  file:
    path: /etc/profile.d/rbenv-load.sh
    state: absent

- name: install & update rbenv
  become: yes
  become_user: "{{user}}"
  shell: |
    #!/usr/bin/env bash
    set -eux
    rm -rf ~/.rbenv/plugins
    curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash

