- name: make sure service {{item.value.name}} is stopped
  service:
    name: madek_{{item.value.name}}
    state: stopped
  failed_when: false
  with_dict: "{{madek_services}}"

- include_tasks: setup-service.yml
  with_dict: "{{madek_services}}"
  tags: [deploy-setup-services]

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: start services
  service:
    name: madek_{{item.value.name}}
    state: restarted
    enabled: yes
  with_dict: "{{madek_services}}"
  when: "item.value.active"

- name: wait for services
  wait_for:
    host: localhost
    port: "{{item.value.http_port}}"
    timeout: 180
  with_dict: "{{madek_services}}"
  when: "item.value.active and item.value.http_port is defined"
