- name: register ruby version
  shell: |
    set -eu
    source ~/.asdf/asdf.sh
    cd {{service_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{service_dir}}"
    executable: /bin/bash
  become: yes
  become_user: "{{madek_user}}"
  become_method: sudo
  register: madek_ruby_version
  changed_when: false

- set_fact:
    ruby_dir: "/home/{{madek_user}}/.asdf/installs/ruby/{{madek_ruby_version.stdout}}"

- template:
    src: cron.service
    dest: /etc/systemd/system/madek_{{service.name}}_cron.service
    mode: 0644
  name: copy madek_{{service.name}}_cron.service

- template:
    src: cron.service
    dest: /etc/systemd/system/madek_{{service.name}}_cron.service
    mode: 0644
  name: install madek_{{service.name}}_cron.service

- template:
    src: cron.timer
    dest: /etc/systemd/system/madek_{{service.name}}_cron.timer
    mode: 0644
  name: install madek_{{service.name}}_cron.timer

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
