- set_fact:
    service: "{{item.value}}"

- set_fact:
    service_dir: "{{madek_server_dir}}{{service.path}}"

- name: setup {{service.name}} java service
  template:
    src: java.service
    dest: /etc/systemd/system/madek_{{service.name}}.service
  when: service.type == 'java'

- name: setup {{service.name}} rails service
  template:
    src: rails.service
    dest: /etc/systemd/system/madek_{{service.name}}.service
  when: service.type == 'rails'
