- set_fact:
    service: "{{item.value}}"
  tags: [always]

- debug:
    msg: Setting up {{service}}

- set_fact:
    service_dir: "{{madek_server_dir}}{{service.dir}}"

- name: setup {{service.name}} java service
  template:
    src: java.service
    dest: /etc/systemd/system/madek_{{service.name}}.service
  when: "service.active and service.type == 'java'"

- include: setup-rails-service.yml
  when: "service.active and service.type == 'rails'"


