# puma wants to set a pidfile now
- name: make tmp/pids
  file:
    path: '{{service_dir}}/tmp/pids'
    state: directory
    recurse: yes
    owner: '{{madek_user}}'
    group: '{{madek_user}}'

- name: install ruby
  shell: |
    #/usr/bin/env bash
    set -euo pipefail
    cd {{service_dir}}
    source ~/.asdf/asdf.sh
    asdf install ruby
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{madek_user}}"
  become_method: sudo

- name: bundle
  shell: |
    #/usr/bin/env bash
    set -euo pipefail
    source ~/.asdf/asdf.sh
    cd {{service_dir}}
    bundle install
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{madek_user}}"
  become_method: sudo
  async: 3600
  poll: 1

- name: register ruby version
  shell: |
    set -eu
    source ~/.asdf/asdf.sh
    cd {{service_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{service_dir}}"
    executable: /bin/bash
  become: yes
  become_user: "{{madek_user}}"
  become_method: sudo
  register: madek_ruby_version
  changed_when: false

- set_fact:
    ruby_dir: "/home/{{madek_user}}/.asdf/installs/ruby/{{madek_ruby_version.stdout}}"

- name: setup {{service.name}} rails service
  template:
    src: rails.service
    dest: /etc/systemd/system/madek_{{service.name}}.service
  when: "service.active and service.type == 'rails'"
