- set_fact:
    external_hostname: "{{hostvars[groups['madek'][0]]['madek_external_hostname']}}"
    internal_hostname: "{{hostvars[groups['madek'][0]]['ansible_ssh_host']}}"

- name: apache non ssl site
  template:
    src: site.conf
    dest: /etc/apache2/sites-available/{{external_hostname}}.conf
    mode: 0644

- file:
    state: link
    src: /etc/apache2/sites-available/{{external_hostname}}.conf
    dest: /etc/apache2/sites-enabled/{{external_hostname}}.conf

- name: apache ssl site
  template:
    src: site-le-ssl.conf
    dest: /etc/apache2/sites-available/{{external_hostname}}-le-ssl.conf
    mode: 0644

- file:
    state: link
    src: /etc/apache2/sites-available/{{external_hostname}}-le-ssl.conf
    dest: /etc/apache2/sites-enabled/{{external_hostname}}-le-ssl.conf

- service:
    name: apache2
    state: restarted
    enabled: true
