ansible_ssh_host: hfg-madek-prod.ruby.zhdk.ch
ansible_ssh_user: root

madek_vim_mode: true

madek_external_hostname: madek.hfg-karlsruhe.de
madek_proxy_add_headers: false

shibboleth_sign_in_enabled: False

madek_master_secret: "{{hfg.madek_master_secret}}"

zencoder_enabled: True
zencoder_api_key: "{{hfg.zencoder_api_key}}"
zencoder_test_mode: False

madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/originals
madek_thumbnail_storage_dir: /opt/madekdata/thumbnails
madek_tmp_dir: /opt/madekdata/tmp
# setting up proper owner etc  is very slow and should only be necessary
# when we switch servers or something
setup_storage_directories: no

db_backups_enabled: True
db_backups_dir: /opt/madekdata/backups

prtg_monitoring: "{{hfg.prtg_monitoring}}" # from `secrets.yml`
