ansible_ssh_host: prod-hslu.madek.zhdk.ch
ansible_ssh_user: root

madek_vim_mode: true

madek_external_hostname: hslu.zhdk.ch

shibboleth_sign_in_enabled: True
shibboleth_sign_in_url: 'https://madek.hslu.zhdk.ch/Shibboleth.sso/Login?target=https%3A%2F%2Fmadek.hslu.zhdk.ch%2FShibboleth.sso%2FSession'.freeze
shibboleth_gateway_ip: 195.176.247.169

madek_master_secret: '{{hslu.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: False

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp

db_backups_enabled: True
db_backups_dir: /opt/madekdata/backups
