ansible_ssh_host: staging-hslu.madek.zhdk.ch
ansible_ssh_user: root

madek_vim_mode: true

madek_external_hostname: staging.hslu.madek.zhdk.ch

madek_master_secret: '{{hslu.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp

madek_webapp_html_extra_head_end: |
    <!-- Staging Note -->
    <style>
          body:before {
            color: red; font: bolder 2em monospace;
            text-align: center;
            width: 100%;
            display: inline-block;
            content: 'THIS IS A STAGING ENVIRONMENT! UPLOAD DOES NOT WORK! CHANGES ARE EPHEMERAL!';
          }
    </style>
    <!-- End Staging Note -->


