madek_external_hostname: madek-spiel.kiste.li
# connection
ansible_ssh_host: spiel1.ruby.zhdk.ch
ansible_ssh_port: 22
ansible_ssh_user: root

# storage
setup_storage_directories: true
madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/files
madek_thumbnail_storage_dir: /opt/madekdata/thumbs
madek_tmp_dir: /opt/madekdata/tmp

# settings
zhdk_integration: True
madek_disallow_search_engine_crawlers: yes
madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]

madek_feature_toggle_admin_sql_reports: "on my own risk"

# create a default admin on this box
admin_login: admin
admin_password: "{{spiel1.admin_password}}"
madek_master_secret: "{{spiel1.madek_master_secret}}"

# zencoder
# # audio and videos previews
# zencoder_enabled: false
# # zencoder_api_key: '{{zhdk_zencoder_api_key}}'
# # zencoder_test_mode: True
zencoder_enabled: True
zencoder_api_key: "{{zhdk_zencoder_api_key}}"
zencoder_test_mode: False

# backups
# db_backups_enabled: False

# customize
madek_webapp_html_extra_head_start: |
  <!-- powered by Madek -->

madek_webapp_html_extra_head_end: |
  <link rel=stylesheet type=text/css href=/assets/local-theme-{{ lookup('pipe','shasum -p -a256 "inventories/zhdk/extensions/local-theme-spiel1.css" | cut -d" " -f1') }}.css>
