ansible_ssh_host: medienarchiv.zhdk.ch
ansible_ssh_user: root

# setting up proper owner etc  is very slow and should only be necessary
# when we switch servers or something
setup_storage_directories: no

madek_welcome_title: false
madek_site_title: false

madek_external_hostname: medienarchiv.zhdk.ch
madek_external_base_url: https://{{ madek_external_hostname }}


madek_master_secret: '{{medienarchiv.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: False

db_backups_enabled: True
db_backups_dir: /opt/madekdata/backups

zhdk_integration: True

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp

madek_webapp_html_extra_body_start: |
    <!-- Piwik Image Tracker-->
    <img src="https://analytics.zhdk.ch/piwik.php?idsite=174&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
    <!-- End Piwik -->

madek_virtual_hosts:
- hostname: '{{madek_external_hostname}}'
  ip: '*'
  ssl_certificate_file: /etc/letsencrypt/live/medienarchiv.zhdk.ch/fullchain.pem
  ssl_certificate_key_file: /etc/letsencrypt/live/medienarchiv.zhdk.ch/privkey.pem
  force_redirect_to_https: yes
