###############################################################################
### ansible stuff #############################################################
###############################################################################

ansible_ssh_host: medienarchiv.zhdk.ch
ansible_ssh_user: root


###############################################################################
### URL etc ###################################################################
###############################################################################

madek_external_hostname: medienarchiv.zhdk.ch


###############################################################################
### ZHdK ######################################################################
###############################################################################

zhdk_integration: True
zhdk_agw_api_key: "{{zhdk_agw_api_prod_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_prod_app}}"


###############################################################################
### database (deployment) handlling ###########################################
###############################################################################

db_backups_enabled: True
db_backups_dir: /opt/madekdata/backups
# restore_structure_and_data: no
# madek_feature_toggle_admin_sql_reports: "on my own risk"


###############################################################################
### file storage ##############################################################
###############################################################################

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp
setup_storage_directories: no  # adjusts permissions, very slow, usually not necessary



###############################################################################
### ldap user, group sync #####################################################
###############################################################################

zhdk_sync_api_token: "{{medienarchiv.zhdk_sync_api_token}}" # from `secrets.yml`
zhdk_sync_ldap_password: "{{zhdk_ldap_password}}" # from `secrets.yml`



###############################################################################
### transcoding ###############################################################
###############################################################################

zencoder_enabled: True
zencoder_api_key: "{{zhdk_zencoder_api_key}}"
zencoder_test_mode: False


###############################################################################
### monitoring ################################################################
###############################################################################

prtg_monitoring: "{{medienarchiv.prtg_monitoring}}" # from `secrets.yml`


###############################################################################
### crawler, SEO ##############################################################
###############################################################################

madek_disallow_search_engine_crawlers: no
madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]


###############################################################################
### other #####################################################################
###############################################################################

madek_master_secret: "{{medienarchiv.madek_master_secret}}"


###############################################################################
### UI and appearance #########################################################
###############################################################################

madek_welcome_title: false
madek_site_title: false

madek_support_email: 'support.medienarchiv@zhdk.ch'

madek_webapp_html_extra_body_start: |
  <!-- Piwik Image Tracker-->
  <img src="https://analytics.zhdk.ch/piwik.php?idsite=174&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
  <!-- End Piwik -->

madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/letsencrypt/live/medienarchiv.zhdk.ch/fullchain.pem
    ssl_certificate_key_file: /etc/letsencrypt/live/medienarchiv.zhdk.ch/privkey.pem
    force_redirect_to_https: yes
