################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{medienarchiv.madek_master_secret}}"

###############################################################################
### reverse proxy #############################################################
###############################################################################


madek_virtual_hosts:

  - hostname: 'medienarchiv.zhdk.ch'
    ip: '*'
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.key
    force_redirect_to_https: yes

    custom_config: |

        RewriteEngine On


        ### redirect to zhdk.medienarchiv.ch >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        # zhdk server network:
        RewriteCond expr "! -R '195.176.247.0/24'"

        # snowflake IPs:
        RewriteCond %{REMOTE_ADDR} !=185.17.69.82
        RewriteCond %{REMOTE_ADDR} !=185.17.69.91
        RewriteCond %{REMOTE_ADDR} !=185.17.69.92
        RewriteCond %{REMOTE_ADDR} !=91.199.98.56

        # googlebot IPs:
        {% for ip in googlebot_ips %}
        RewriteCond %{REMOTE_ADDR} !=35.158.0.0/16
        {% endfor}

        # static test IP:
        RewriteCond %{REMOTE_ADDR} !=213.144.130.166

        # video encoding via Zencoder:
        RewriteCond "%{REQUEST_URI}?%{QUERY_STRING}" !^/files/([a-fA-F0-9\-]+)\?access_token=([a-fA-F0-9\-]+)$
        RewriteCond "%{REQUEST_URI}"  !^/zencoder_jobs/(.*)$

        RewriteRule ^(.*)$ https://zhdk.medienarchiv.ch$1 [R=307,L]

        ### redirect to zhdk.medienarchiv.ch <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


  - hostname: 'zhdk.medienarchiv.ch'
    ip: '*'
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.key
    force_redirect_to_https: yes


madek_disallow_search_engine_crawlers: no


###############################################################################
### storage settings ##########################################################
###############################################################################

# they are already there,
# owner and permissions settings very slow, enable only if needed

setup_storage_directories: false
madek_tmp_dir: /opt/madekdata/tmp


###############################################################################
### database and db backups ###################################################
###############################################################################

db_backups_enabled: True
restore_structure_and_data: False


###############################################################################
### transcoding settings ######################################################
###############################################################################

zencoder_test_mode: False


##############################################################################
### services ##################################################################
###############################################################################

madek_webapp_puma_worker_killer_enabled: false

madek_webapp_html_extra_body_start: |
  <!-- Piwik Image Tracker-->
  <img src="https://analytics.zhdk.ch/piwik.php?idsite=174&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
  <!-- End Piwik -->


###############################################################################
###  zhdk config ##############################################################
###############################################################################

zhdk_agw_api_id: "{{zhdk_agw_api_prod_app}}"
zhdk_agw_api_key: "{{zhdk_agw_api_prod_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_prod_app}}"

webstats_enabled: True
webstats_passwords_set:
  Madek: "{{madek_prod_webstats_password}}"
