################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{medienarchiv.madek_master_secret}}"

###############################################################################
### reverse proxy #############################################################
###############################################################################


madek_virtual_hosts:

  - hostname: 'medienarchiv.zhdk.ch'
    ip: '*'
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.key
    force_redirect_to_https: yes

    custom_config: |

        RewriteEngine On


        ### redirect to zhdk.medienarchiv.ch >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        # zhdk server network:
        RewriteCond expr "! -R '195.176.247.0/24'"
        RewriteCond expr "! -R '10.0.0.0/8'"

        # snowflake IPs:
        RewriteCond %{REMOTE_ADDR} !=185.17.69.82
        RewriteCond %{REMOTE_ADDR} !=185.17.69.91
        RewriteCond %{REMOTE_ADDR} !=185.17.69.92
        RewriteCond %{REMOTE_ADDR} !=91.199.98.56

        # static test IP:
        RewriteCond %{REMOTE_ADDR} !=213.144.130.166
        RewriteCond expr "! -R '2001:1620:9a6::/48'"

        # video encoding via Zencoder:
        RewriteCond "%{REQUEST_URI}?%{QUERY_STRING}" !^/files/([a-fA-F0-9\-]+)\?access_token=([a-fA-F0-9\-]+)$
        RewriteCond "%{REQUEST_URI}"  !^/zencoder_jobs/(.*)$

        # do not redirect googlebot IPs:
        {% set googlebot_data = lookup('url', 'https://developers.google.com/search/apis/ipranges/googlebot.json', split_lines=False) | from_json %}
        {% set googlebot_ips = googlebot_data.prefixes | selectattr('ipv4Prefix', 'defined') | map(attribute='ipv4Prefix') | list + googlebot_data.prefixes | selectattr('ipv6Prefix', 'defined') | map(attribute='ipv6Prefix') | list %}
        {% for ip in googlebot_ips %}
        RewriteCond expr "! -R '{{ ip }}'"
        {% endfor %}

        # do not redirect bingbot IPs:
        {% set bingbot_data = lookup('url', 'https://www.bing.com/toolbox/bingbot.json', split_lines=False) | from_json %}
        {% set bingbot_ips = bingbot_data.prefixes | selectattr('ipv4Prefix', 'defined') | map(attribute='ipv4Prefix') | list + bingbot_data.prefixes | selectattr('ipv6Prefix', 'defined') | map(attribute='ipv6Prefix') | list %}
        {% for ip in bingbot_ips %}
        RewriteCond expr "! -R '{{ ip }}'"
        {% endfor %}

        # Rewrite to CF zhdk.medienarchiv.ch :
        RewriteRule ^(.*)$ https://zhdk.medienarchiv.ch$1 [R=307,L]

        ### redirect to zhdk.medienarchiv.ch <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


  - hostname: 'zhdk.medienarchiv.ch'
    ip: '*'
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.key
    force_redirect_to_https: yes
    custom_config: |

        RewriteEngine On

        # static test IP:
        RewriteCond expr "-R '213.144.130.166/32'" [OR]
        RewriteCond expr "-R '2001:1620:9a6::/48'" [OR]

        # zhdk server network:
        RewriteCond expr "-R '195.176.247.0/24'" [OR]
        # zhdk internal network:
        RewriteCond expr "-R '10.0.0.0/8'" [OR]

        # EXPERIMENTAL TO BE TESTED:
        # zhdk external IP for HTTP
        RewriteCond expr "-R '195.176.29.132/32'" [OR]


        # force googlebot IPs to use medienarchiv.zhdk.ch:
        {% set googlebot_data = lookup('url', 'https://developers.google.com/search/apis/ipranges/googlebot.json', split_lines=False) | from_json %}
        {% set googlebot_ips = googlebot_data.prefixes | selectattr('ipv4Prefix', 'defined') | map(attribute='ipv4Prefix') | list + googlebot_data.prefixes | selectattr('ipv6Prefix', 'defined') | map(attribute='ipv6Prefix') | list %}
        {% for ip in googlebot_ips %}
        RewriteCond expr "-R '{{ ip }}'" [OR]
        {% endfor %}

        # force bingbot IPs to use medienarchiv.zhdk.ch:
        {% set bingbot_data = lookup('url', 'https://www.bing.com/toolbox/bingbot.json', split_lines=False) | from_json %}
        {% set bingbot_ips = bingbot_data.prefixes | selectattr('ipv4Prefix', 'defined') | map(attribute='ipv4Prefix') | list + bingbot_data.prefixes | selectattr('ipv6Prefix', 'defined') | map(attribute='ipv6Prefix') | list %}
        {% for ip in bingbot_ips %}
        RewriteCond expr "-R '{{ ip }}'" [OR]
        {% endfor %}


        # DO NOT REMOVE THIS CONDITION AND KEEP IT AS LAST CONDITION!
        # the last condition must not be terminated by an [OR]
        # ::/128 "unspecified address" (equivalent to 0.0.0.0 in IPv4)
        RewriteCond expr "-R '::/128'"

        RewriteRule ^(.*)$ https://medienarchiv.zhdk.ch$1 [R=308,L]



madek_disallow_search_engine_crawlers: no


###############################################################################
### storage settings ##########################################################
###############################################################################

# they are already there,
# owner and permissions settings very slow, enable only if needed

setup_storage_directories: false
madek_tmp_dir: /opt/madekdata/tmp


###############################################################################
### database and db backups ###################################################
###############################################################################

db_backups_enabled: True
restore_structure_and_data: False

db_backup_service_custom_extend: |
  # Notify monitoring system, note: this must be a single line without line breaks!
  ExecStart=curl -X POST http://10.158.0.30:5050/74CEB0CD-F039-406A-9337-51953ED8F569 -H "Content-Type: application/json" -d '{"prtg": {"result": [ { "channel": "Success", "value": 1, "customUnit": "bool" } ]}}'


###############################################################################
### transcoding settings ######################################################
###############################################################################

zencoder_test_mode: False
zencoder_private_mode: True


##############################################################################
### services ##################################################################
###############################################################################

madek_webapp_puma_worker_killer_enabled: false

madek_webapp_html_extra_body_start: |
  <!-- Piwik Image Tracker-->
  <img src="https://analytics.zhdk.ch/piwik.php?idsite=174&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
  <!-- End Piwik -->


###############################################################################
###  zhdk config ##############################################################
###############################################################################

zhdk_agw_api_id: "{{zhdk_agw_api_prod_app}}"
zhdk_agw_api_key: "{{zhdk_agw_api_prod_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_prod_app}}"

webstats_enabled: True
webstats_passwords_set:
  Madek: "{{madek_prod_webstats_password}}"



###############################################################################
### sync config and secrets ###################################################
###############################################################################

madek_zapi_sync_api_token: '{{zhdk_sync_api_token}}'
madek_zapi_sync_secret: '{{zapi_sync_prod_key}}'


