################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{medienarchiv.madek_master_secret}}"

###############################################################################
### reverse proxy #############################################################
###############################################################################


madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-prod.ruby.zhdk.ch.key
    force_redirect_to_https: yes

madek_disallow_search_engine_crawlers: no


###############################################################################
### storage settings ##########################################################
###############################################################################

# they are already there,
# owner and permissions settings very slow, enable only if needed

setup_storage_directories: false
madek_tmp_dir: /opt/madekdata/tmp


###############################################################################
### database and db backups ###################################################
###############################################################################

db_backups_enabled: True
restore_structure_and_data: False


###############################################################################
### transcoding settings ######################################################
###############################################################################

zencoder_test_mode: False


##############################################################################
### services ##################################################################
###############################################################################

madek_webapp_puma_worker_killer_enabled: false

madek_webapp_html_extra_body_start: |
  <!-- Piwik Image Tracker-->
  <img src="https://analytics.zhdk.ch/piwik.php?idsite=174&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
  <!-- End Piwik -->


###############################################################################
###  zhdk config ##############################################################
###############################################################################

zhdk_agw_api_id: "{{zhdk_agw_api_prod_app}}"
zhdk_agw_api_key: "{{zhdk_agw_api_prod_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_prod_app}}"

webstats_enabled: True
webstats_passwords_set:
  Madek: "{{madek_zhdk_basic_auth_password}}"
