################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{staging.madek_master_secret}}"


###############################################################################
### reverse proxy #############################################################
###############################################################################

madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-staging.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-staging.ruby.zhdk.ch.key
    force_redirect_to_https: yes
