###############################################################################
### ansible stuff #############################################################
###############################################################################

ansible_ssh_host: staging.madek.zhdk.ch
ansible_ssh_user: root

###############################################################################
### URL etc ###################################################################
###############################################################################

madek_external_hostname: staging.madek.zhdk.ch

###############################################################################
### ZHdK ######################################################################
###############################################################################

zhdk_integration: True
zhdk_agw_api_key: "{{zhdk_agw_api_test_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_test_app}}"

###############################################################################
### database (deployment) handlling ###########################################
###############################################################################

db_backups_enabled: False
# db_backups_dir: /opt/madekdata/backups
restore_structure_and_data: yes
madek_feature_toggle_admin_sql_reports: "on my own risk"

###############################################################################
### file storage ##############################################################
###############################################################################

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
#madek_tmp_dir: /opt/madekdata/tmp # use default tmp dir, not datadir (mounted read-only)
setup_storage_directories: no # dont do it, files are mounted read-only!

###############################################################################
### transcoding ###############################################################
###############################################################################

zencoder_enabled: True
zencoder_api_key: "{{zhdk_zencoder_api_key}}"
zencoder_test_mode: True

###############################################################################
### monitoring ################################################################
###############################################################################

# prtg_monitoring: "{{staging.prtg_monitoring}}" # from `secrets.yml`

###############################################################################
### crawler, SEO ##############################################################
###############################################################################

madek_disallow_search_engine_crawlers: yes
madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]

###############################################################################
### other #####################################################################
###############################################################################

madek_master_secret: "{{staging.madek_master_secret}}"

###############################################################################
### UI and appearance #########################################################
###############################################################################

# madek_welcome_title: false
# madek_site_title: false

madek_webapp_html_extra_head_end: |
  <style>
  {{ lookup('file', 'inventories/zhdk/files/logo-style-zhdk.css') }}
  </style>
  <!-- FROM HERE OVERRIDE only staging.madek -->

  <!-- uploader notice: -->
  <style>
    [data-react-class="UI.Views.My.Uploader"]:before {
      color: red; font: bolder 3em monospace;
      content: 'NOTE! THIS IS A STAGING SERVER! UPLOAD DOES NOT WORK!';
    }
  </style>

  <!-- custom CSS demo -->
  <style>
  {{ lookup('file', 'files/custom-css-demo.css') }}
  </style>
