###############################################################################
### ansible stuff #############################################################
###############################################################################

ansible_ssh_host: zhdk-madek-staging.ruby.zhdk.ch
ansible_ssh_user: root

###############################################################################
### URL etc ###################################################################
###############################################################################

madek_external_hostname: staging.madek.zhdk.ch

###############################################################################
### ZHdK ######################################################################
###############################################################################

zhdk_integration: True
zhdk_agw_api_id: madektest
zhdk_agw_api_key: "{{zhdk_agw_api_test_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_test_app}}"

agw_auth_public_key: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJCGE8RbZhtTj+93HMSkSKMbWv4/X
  +87MRVYtJMoYSa3F9HONSSCkSbCNcpz4QBqLLcd4KCJGUFHCRowp4Trw0Q==
  -----END PUBLIC KEY-----

agw_auth_madek_public_key: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfv30vIA7yLtLDf2ISVCohxmh1Tby
  4cPaxmCiXbFes2IqlYDDVk0hdk8q8/OFKKKfWGd90c7V6n9zJsr0Xs22ug==
  -----END PUBLIC KEY-----



###############################################################################
### database (deployment) handlling ###########################################
###############################################################################

db_backups_enabled: False
# db_backups_dir: /opt/madekdata/backups
restore_structure_and_data: yes
madek_feature_toggle_admin_sql_reports: "on my own risk"

###############################################################################
### file storage ##############################################################
###############################################################################

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
#madek_tmp_dir: /opt/madekdata/tmp # use default tmp dir, not datadir (mounted read-only)
setup_storage_directories: no # dont do it, files are mounted read-only!

###############################################################################
### transcoding ###############################################################
###############################################################################

zencoder_enabled: True
zencoder_api_key: "{{zhdk_zencoder_api_key}}"
zencoder_test_mode: True

###############################################################################
### crawler, SEO ##############################################################
###############################################################################

madek_disallow_search_engine_crawlers: yes
madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]

###############################################################################
### other #####################################################################
###############################################################################

madek_master_secret: "{{staging.madek_master_secret}}"

###############################################################################
### UI and appearance #########################################################
###############################################################################

# madek_welcome_title: false
# madek_site_title: false

madek_webapp_html_extra_head_end: |
  <style>
  {{ lookup('file', 'inventories/zhdk/files/logo-style-zhdk.css') }}
  </style>
  <!-- FROM HERE OVERRIDE only staging.madek -->

  <!-- uploader notice: -->
  <style>
    [data-react-class="UI.Views.My.Uploader"]:before {
      color: red; font: bolder 3em monospace;
      content: 'NOTE! THIS IS A STAGING SERVER! UPLOAD DOES NOT WORK!';
    }
  </style>

  <!-- custom CSS demo -->
  <style>
  {{ lookup('file', 'files/custom-css-demo.css') }}
  </style>




###############################################################################
### Custom Reverse Proxy Settings #############################################
###############################################################################


reverse_proxy_custom_templates:
  'test.htpasswd':  'auth.htpasswd'

reverse_proxy_custom_config: |

  ProxyPass /zhdk-agw  http://localhost:3333/zhdk-agw    nocanon retry=0

  <LocationMatch "^(?!/api.*)" >
      AuthType Basic
      AuthName "ZHdK Madek {{madek_external_hostname}}"
      AuthBasicProvider file
      AuthUserFile "/etc/apache2/madek/auth.htpasswd"
      Require valid-user
  </LocationMatch>


###############################################################################
### Certs #####################################################################
###############################################################################


madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-staging.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-staging.ruby.zhdk.ch.key
    force_redirect_to_https: yes
