ansible_ssh_host: staging.madek.zhdk.ch
ansible_ssh_user: root

madek_external_hostname: staging.madek.zhdk.ch

zhdk_integration: True

madek_master_secret: '{{staging.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True

setup_storage_directories: false

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp

restore_structure_and_data: yes

db_backups_enabled: False

madek_webapp_html_extra_head_end: |
  <style>
    [data-react-class="UI.Views.My.Uploader"]:before {
      color: red; font: bolder 3em monospace;
      content: 'NOTE! THIS IS A STAGING SERVER! UPLOAD DOES NOT WORK!';
    }
  </style>
