madek_host_name: staging-v3-pdata.madek.zhdk.ch

madek_master_secret: '{{staging_v3_pdata.madek_master_secret}}'

setup_storage_directories: false

file_storage_dir: /opt/madekdata/attachments
thumbnail_storage_dir: /opt/madekdata/attachments

db_backups_enabled: False
