madek_external_hostname: staging-v3-pdata.madek.zhdk.ch

madek_master_secret: '{{staging_v3_pdata.madek_master_secret}}'

setup_storage_directories: false

madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments

db_backups_enabled: False
