ansible_ssh_host: test.madek.zhdk.ch
ansible_ssh_user: root

madek_external_hostname: test.madek.zhdk.ch

zhdk_integration: True

madek_master_secret: '{{test.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True

setup_storage_directories: false

madek_storage_dir: /opt/madekdata
madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments
madek_tmp_dir: /opt/madekdata/tmp

restore_structure_and_data: yes

db_backups_enabled: False

madek_feature_toggle_admin_sql_reports: "on my own risk"

webapp_html_extra_content:
  body_start: |
    <!-- Piwik Image Tracker-->
    <img src="https://analytics.zhdk.ch/piwik.php?idsite=172&rec=1" style="border:0;position:fixed;top:0;left:0" alt="">
    <!-- End Piwik -->

  head_end: |
    <style>
      [data-react-class="UI.Views.My.Uploader"]:before {
        color: red; font: bolder 3em monospace;
        content: 'NOTE! THIS IS A TEST SERVER! UPLOAD DOES NOT WORK!';
      }
      </style>
