madek_host_name: test8.madek.zhdk.ch

db_backups_enabled: False

ssh_keys:
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/cislave_madek')}}"
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/drtom')}}"
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/mfa')}}"
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/michael')}}"
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/nimaai')}}"
  - "{{lookup('file', './inventories/zhdk/shared/ssh_keys/rca')}}"

