###############################################################################
### ansible stuff #############################################################
###############################################################################

ansible_ssh_host: zhdk-madek-test-blank.ruby.zhdk.ch
ansible_ssh_user: root

###############################################################################
### URL etc ###################################################################
###############################################################################

madek_external_hostname: test-blank.madek.zhdk.ch

###############################################################################
### ZHdK ######################################################################
###############################################################################

zhdk_integration: True
zhdk_agw_api_key: "{{zhdk_agw_api_test_key}}"
zhdk_agw_api_url: "https://intern.zhdk.ch/?auth/{{zhdk_agw_api_test_app}}"

agw_auth_public_key: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJCGE8RbZhtTj+93HMSkSKMbWv4/X
  +87MRVYtJMoYSa3F9HONSSCkSbCNcpz4QBqLLcd4KCJGUFHCRowp4Trw0Q==
  -----END PUBLIC KEY-----

agw_auth_madek_public_key: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfv30vIA7yLtLDf2ISVCohxmh1Tby
  4cPaxmCiXbFes2IqlYDDVk0hdk8q8/OFKKKfWGd90c7V6n9zJsr0Xs22ug==
  -----END PUBLIC KEY-----



shibboleth_sign_in_enabled: False # disabled because package is broken…

###############################################################################
### database (deployment) handlling ###########################################
###############################################################################

drop_database: yes
db_backups_enabled: False
# db_backups_dir: /opt/madekdata/backups
restore_structure_and_data: no
madek_feature_toggle_admin_sql_reports: "on my own risk"

###############################################################################
### file storage ##############################################################
###############################################################################

#madek_storage_dir: /tmp
#madek_file_storage_dir: /opt/madekdata/attachments
#madek_thumbnail_storage_dir: /opt/madekdata/attachments
#madek_tmp_dir: /opt/madekdata/tmp
setup_storage_directories: True

###############################################################################
### transcoding ###############################################################
###############################################################################

zencoder_enabled: True
zencoder_api_key: "{{zhdk_zencoder_api_key}}"
zencoder_test_mode: True


###############################################################################
### crawler, SEO ##############################################################
###############################################################################

madek_disallow_search_engine_crawlers: yes
madek_block_useragents:
  ["AhrefsBot", "SemrushBot", "PiplBot", "seo4ajax", "BLEXBot"]

###############################################################################
### other #####################################################################
###############################################################################

madek_master_secret: "{{test_blank.madek_master_secret}}"

# create a default admin on this box
admin_login: admin
admin_password: "{{test_blank.admin_password}}"

###############################################################################
### UI and appearance #########################################################
###############################################################################

# madek_welcome_title: false
# madek_site_title: false

madek_webapp_html_extra_head_start: |
  <!--
       __       __                  __            __
  /  \     /  |                /  |          /  |
  $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
  $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
  $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
  $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
  $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
  $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
  $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/

    ▄▄▄█████▓▓█████   ██████ ▄▄▄█████▓
  ▓  ██▒ ▓▒▓█   ▀ ▒██    ▒ ▓  ██▒ ▓▒
  ▒ ▓██░ ▒░▒███   ░ ▓██▄   ▒ ▓██░ ▒░
  ░ ▓██▓ ░ ▒▓█  ▄   ▒   ██▒░ ▓██▓ ░
    ▒██▒ ░ ░▒████▒▒██████▒▒  ▒██▒ ░
    ▒ ░░   ░░ ▒░ ░▒ ▒▓▒ ▒ ░  ▒ ░░
      ░     ░ ░  ░░ ░▒  ░ ░    ░
    ░         ░   ░  ░  ░    ░
              ░  ░      ░

  -->


###############################################################################
### Custom Reverse Proxy Settings #############################################
###############################################################################



reverse_proxy_custom_templates:
  'test.htpasswd':  'auth.htpasswd'

reverse_proxy_custom_config: |


  ProxyPass /zhdk-agw  http://localhost:3333/zhdk-agw    nocanon retry=0

  <LocationMatch "^(?!/api.*)" >
      AuthType Basic
      AuthName "ZHdK Madek {{madek_external_hostname}}"
      AuthBasicProvider file
      AuthUserFile "/etc/apache2/madek/auth.htpasswd"
      Require valid-user
  </LocationMatch>


###############################################################################
### Certs #####################################################################
###############################################################################


madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.key
    force_redirect_to_https: yes

