################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{test_blank.madek_master_secret}}"


###############################################################################
### reverse proxy #############################################################
###############################################################################

madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.key
    force_redirect_to_https: yes


  
###############################################################################
### storage settings ##########################################################
###############################################################################




setup_storage_directories: true
madek_storage_dir: /var/local/madek-file-storage
madek_file_storage_dir: "{{madek_storage_dir}}/originals"
madek_thumbnail_storage_dir: "{{madek_storage_dir}}/thumbnails"


restrict_access_via_basic_auth: False


###############################################################################
### database and db backups ###################################################
###############################################################################

drop_database: yes
db_backups_enabled: False
# db_backups_dir: /opt/madekdata/backups
restore_structure_and_data: no
madek_feature_toggle_admin_sql_reports: "on my own risk"




##############################################################################
### services ##################################################################
###############################################################################


### webapp #####################################################################


madek_webapp_html_extra_head_start: |
  <!--
       __       __                  __            __
  /  \     /  |                /  |          /  |
  $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
  $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
  $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
  $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
  $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
  $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
  $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/

    ▄▄▄█████▓▓█████   ██████ ▄▄▄█████▓
  ▓  ██▒ ▓▒▓█   ▀ ▒██    ▒ ▓  ██▒ ▓▒
  ▒ ▓██░ ▒░▒███   ░ ▓██▄   ▒ ▓██░ ▒░
  ░ ▓██▓ ░ ▒▓█  ▄   ▒   ██▒░ ▓██▓ ░
    ▒██▒ ░ ░▒████▒▒██████▒▒  ▒██▒ ░
    ▒ ░░   ░░ ▒░ ░▒ ▒▓▒ ▒ ░  ▒ ░░
      ░     ░ ░  ░░ ░▒  ░ ░    ░
    ░         ░   ░  ░  ░    ░
              ░  ░      ░

  -->


###############################################################################
### other #####################################################################
###############################################################################


# create a default admin on this box
admin_login: admin
admin_password: "{{test_blank.admin_password}}"
