ansible_ssh_host: test-blank.madek.zhdk.ch
ansible_ssh_user: root

madek_external_hostname: test-blank.madek.zhdk.ch

zhdk_integration: True
shibboleth_sign_in: False # disabled because package is broken…

madek_master_secret: '{{test_blank.madek_master_secret}}'

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True
zencoder_audio_output_formats_defaults: [{audio_codec: 'vorbis', skip_video: true}, {audio_codec: 'mp3', skip_video: true}]

setup_storage_directories: True

#madek_storage_dir: /tmp
#madek_file_storage_dir: /opt/madekdata/attachments
#madek_thumbnail_storage_dir: /opt/madekdata/attachments
#madek_tmp_dir: /opt/madekdata/tmp

restore_structure_and_data: no
drop_database: yes

db_backups_enabled: False

# create a default admin on this box
admin_login: admin
admin_password: '{{test_blank.admin_password}}'
