################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{test_blank.madek_master_secret}}"


###############################################################################
### reverse proxy #############################################################
###############################################################################

madek_virtual_hosts:
  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.key
    force_redirect_to_https: yes
    custom_config: |

        RewriteEngine On

        ### CORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Headers "Authorization"
        Header always set Access-Control-Allow-Methods "GET"
        Header always set Access-Control-Expose-Headers "Content-Security-Policy, Location"
        Header always set Access-Control-Max-Age "600"

        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ $1 [R=200,L]

        ### CORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<





  - hostname: "cftest.madek.zhdk.ch"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.key
    force_redirect_to_https: yes
    custom_config: |

        RewriteEngine On


        ### CORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Headers "Authorization"
        Header always set Access-Control-Allow-Methods "GET"
        Header always set Access-Control-Expose-Headers "Content-Security-Policy, Location"
        Header always set Access-Control-Max-Age "600"

        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ $1 [R=200,L]

        ### CORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



        ### redirect to www.medienarchiv-cf-test.org >>>>>>>>>>>>>>>>>>>>>>>>>>>

        # zhdk server network:
        RewriteCond expr "! -R '195.176.247.0/24'"

        # snowflake IPs:
        RewriteCond %{REMOTE_ADDR} !=185.17.69.92
        RewriteCond %{REMOTE_ADDR} !=185.17.69.91
        RewriteCond %{REMOTE_ADDR} !=91.199.98.56

        # static test IP:
        RewriteCond %{REMOTE_ADDR} !=213.144.130.166

        # video encoding via Zencoder:
        RewriteCond "%{REQUEST_URI}?%{QUERY_STRING}" !^/files/([a-fA-F0-9\-]+)\?access_token=([a-fA-F0-9\-]+)$
        RewriteCond "%{REQUEST_URI}"  !^/zencoder_jobs/(.*)$

        # Rewrite to CF:
        RewriteRule ^(.*)$ https://www.medienarchiv-cf-test.org$1 [R=307,L]

        ### redirect to www.medienarchiv-cf-test.org <<<<<<<<<<<<<<<<<<<<<<<<<<<<



  - hostname: "www.medienarchiv-cf-test.org"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test-blank.ruby.zhdk.ch.key
    force_redirect_to_https: yes

    custom_config: |

        RewriteEngine On

        ### CORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Headers "Authorization"
        Header always set Access-Control-Allow-Methods "GET"
        Header always set Access-Control-Expose-Headers "Content-Security-Policy, Location"
        Header always set Access-Control-Max-Age "600"

        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ $1 [R=200,L]

        ### CORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



###############################################################################
### storage settings ##########################################################
###############################################################################

setup_storage_directories: true
madek_storage_dir: /var/local/madek-file-storage
madek_file_storage_dir: "{{madek_storage_dir}}/originals"
madek_thumbnail_storage_dir: "{{madek_storage_dir}}/thumbnails"



###############################################################################
### database and db backups ###################################################
###############################################################################

drop_database: yes
db_backups_enabled: False
# db_backups_dir: /opt/madekdata/backups
restore_structure_and_data: no
madek_feature_toggle_admin_sql_reports: "on my own risk"




##############################################################################
### services ##################################################################
###############################################################################


### webapp #####################################################################


madek_webapp_html_extra_head_start: |
  <!--
       __       __                  __            __
  /  \     /  |                /  |          /  |
  $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
  $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
  $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
  $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
  $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
  $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
  $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/

    ▄▄▄█████▓▓█████   ██████ ▄▄▄█████▓
  ▓  ██▒ ▓▒▓█   ▀ ▒██    ▒ ▓  ██▒ ▓▒
  ▒ ▓██░ ▒░▒███   ░ ▓██▄   ▒ ▓██░ ▒░
  ░ ▓██▓ ░ ▒▓█  ▄   ▒   ██▒░ ▓██▓ ░
    ▒██▒ ░ ░▒████▒▒██████▒▒  ▒██▒ ░
    ▒ ░░   ░░ ▒░ ░▒ ▒▓▒ ▒ ░  ▒ ░░
      ░     ░ ░  ░░ ░▒  ░ ░    ░
    ░         ░   ░  ░  ░    ░
              ░  ░      ░

  -->


###############################################################################
### other #####################################################################
###############################################################################


# create a default admin on this box
admin_login: admin
admin_password: "{{test_blank.admin_password}}"

restrict_access_via_basic_auth: false

