madek_external_hostname: test.madek.zhdk.ch

madek_master_secret: '{{test.madek_master_secret}}'

setup_storage_directories: false

madek_file_storage_dir: /opt/madekdata/attachments
madek_thumbnail_storage_dir: /opt/madekdata/attachments

db_backups_enabled: False

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True
