madek_host_name: test8.madek.zhdk.ch

madek_master_secret: '{{test8.madek_master_secret}}'

db_backups_enabled: False

zencoder_enabled: True
zencoder_api_key: '{{zhdk_zencoder_api_key}}'
zencoder_test_mode: True
