################################################################################
### global settings ############################################################
################################################################################

madek_master_secret: "{{test.madek_master_secret}}"
restrict_access_via_basic_auth: false

# https?://((mfa|nimaai|tom|uvb|manuel)\.madek\.rubydev\.zhdk\.ch|(test|test-blank|staging)\.madek\.zhdk\.ch|https://www\.medienarchiv-cf-test\.org|localhost.*)

###############################################################################
### reverse proxy #############################################################
###############################################################################

madek_virtual_hosts:

  - hostname: "{{madek_external_hostname}}"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.key
    force_redirect_to_https: yes

  - hostname: "cftest.madek.zhdk.ch"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.key
    force_redirect_to_https: yes
    custom_config: |

        # RewriteEngine On
        # rewritecond expr "! -r '10.0.0.0/8'"
        # rewritecond %{remote_addr} !=185.17.69.92
        # rewritecond %{remote_addr} !=195.176.247.181
        # rewritecond %{remote_addr} !=213.144.130.166
        # rewritecond %{remote_addr} !=195.176.247.199
        # rewritecond "%{request_uri}?%{query_string}" !^/files/([a-fa-f0-9\-]+)\?access_token=([a-fa-f0-9\-]+)$
        # rewritecond "%{request_uri}"  !^/zencoder_jobs/(.*)$
        # RewriteRule ^(.*)$ https://www.medienarchiv-cf-test.org$1 [R=307,L]

  - hostname: "www.medienarchiv-cf-test.org"
    ip: "*"
    ssl_certificate_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.crt
    ssl_certificate_key_file: /etc/ssl/localcerts/zhdk-madek-test.ruby.zhdk.ch.key
    force_redirect_to_https: yes
    custom_config: |

        # RewriteEngine On
        # RewriteCond %{REMOTE_ADDR} ==213.144.130.166 [OR]
        # RewriteCond %{REMOTE_ADDR} ==195.176.29.132
        # RewriteRule ^(.*)$ https://cftest.madek.zhdk.ch$1 [R=307,L]

###############################################################################
### other #####################################################################
###############################################################################

madek_run_produce_daily_emails_on: "*-*-* 15:00:00"
madek_run_produce_weekly_emails_on: "*-*-* 15:00:00"
